name: Backend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Zip Lambda function
        run: |
          cd crc-project/backend
          zip -r crc_visitor_counter.zip .
      
      - name: Upload Lambda zip to S3
        run: |
          aws s3 cp crc-project/backend/crc_visitor_counter.zip s3://jericho-crc-site-lambda/crc_visitor_counter.zip
      
      - name: Clean up Lambda zip
        run: |
          rm crc-project/backend/crc_visitor_counter.zip

      - name: Terraform Init
        working-directory: crc-project/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: crc-project/terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_lambda_s3_bucket: jericho-crc-site-lambda
          TF_VAR_lambda_s3_key: crc_visitor_counter.zip
          
